{
 "title": "GPON stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Attenuation sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HSGQ / ODI XPON SoC and GPON signal metrics",
     "type": "text",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "options": {
      "content": "# Common attenuation sources:\n\n- **Upstream Length Loss:** `~0.5 dB` per Km on `1310 nm`.\n- **Downstream Length Loss:** `~0.3 dB` per Km on `1490 nm`.\n- **Splices Loss:** `~0.1 dB` per splice.\n- **Connectors Loss:** `~0.6 dB` per connector.\n- **Splitter Loss:** `log10(split:ratio) x 10 = Attenuation in dB` for each split.\n\nSee - [UISP Fiber: Designing a GPON Network](https://help.ui.com/hc/en-us/articles/115011654907-UISP-Fiber-Designing-a-GPON-Network)"
     }
    }
   ]
  },
  { "title": "CPU / RAM / Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gpon_collector\", instance=\"localhost:8111\"} / (1024^2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpon_voltage_volts {job=\"gpon_collector\", instance=\"localhost:8111\", ip=\"192.168.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"gpon_tx_power_dbm\", instance=\"localhost:8111\", ip=\"192.168.1.1\", job=\"gpon_collector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"gpon_rx_power_dbm\", instance=\"localhost:8111\", ip=\"192.168.1.1\", job=\"gpon_collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature & GPON signal metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "SFP SoC Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "gpon_temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Signal Tx power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "gpon_tx_power_dbm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bias Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    { "expr": "gpon_bias_current_mA", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Signal Rx power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "gpon_rx_power_dbm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PON Tx / Rx Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "gpon_tx_power_dbm", "legendFormat": "__auto" },
    { "expr": "gpon_rx_power_dbm", "legendFormat": "__auto" }
   ]
  }
 ]
}